param (
    [string]$ProjectDir
)

$envPath = Join-Path $ProjectDir "..\.env"
if (-not (Test-Path $envPath)) {
    Write-Error "No .env file found at $envPath"
    exit 1
}

$secret = ""
$url = ""
$supabaseUrl = ""
$supabaseAnonKey = ""

Get-Content $envPath | ForEach-Object {
    $line = $_.Trim()
    if ($line.StartsWith("#") -or $line -eq "") { return }
    
    if ($line -match "^OVERLAY_SYNC_SECRET_HEX\s*=\s*(.*)") {
        $secret = $Matches[1].Trim().Trim('"').Trim("'")
    }
    elseif ($line -match "^OVERLAY_SYNC_BASEURL\s*=\s*(.*)") {
        $url = $Matches[1].Trim().Trim('"').Trim("'")
    }
    elseif ($line -match "^SUPABASE_URL\s*=\s*(.*)") {
        $supabaseUrl = $Matches[1].Trim().Trim('"').Trim("'")
    }
    elseif ($line -match "^SUPABASE_ANON_KEY\s*=\s*(.*)") {
        $supabaseAnonKey = $Matches[1].Trim().Trim('"').Trim("'")
    }
}

if ([string]::IsNullOrEmpty($secret) -or [string]::IsNullOrEmpty($url)) {
    Write-Warning "Could not parse OVERLAY_SYNC_SECRET_HEX or OVERLAY_SYNC_BASEURL from .env file"
}
if ([string]::IsNullOrEmpty($supabaseUrl) -or [string]::IsNullOrEmpty($supabaseAnonKey)) {
    Write-Warning "Could not parse SUPABASE_URL or SUPABASE_ANON_KEY from .env file"
}

$key = [System.Text.Encoding]::UTF8.GetBytes("RUST+DESK")
$secretBytes = [System.Text.Encoding]::UTF8.GetBytes($secret)
$urlBytes = [System.Text.Encoding]::UTF8.GetBytes($url)
$sbUrlBytes = [System.Text.Encoding]::UTF8.GetBytes($supabaseUrl)
$sbAnonBytes = [System.Text.Encoding]::UTF8.GetBytes($supabaseAnonKey)

function Obfuscate($bytes) {
    $enc = New-Object byte[] $bytes.Length
    for ($i=0; $i -lt $bytes.Length; $i++) {
        $enc[$i] = $bytes[$i] -bxor $key[$i % $key.Length]
    }
    return ($enc | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
}

$secretStr = Obfuscate $secretBytes
$urlStr = Obfuscate $urlBytes
$sbUrlStr = Obfuscate $sbUrlBytes
$sbAnonStr = Obfuscate $sbAnonBytes

$code = @"
// <auto-generated />
namespace RustPlusDesk.Services.Data
{
    public static class ObfuscatedSecrets
    {
        public static readonly byte[] ObfuscationKey = new byte[] { 0x52, 0x55, 0x53, 0x54, 0x2b, 0x44, 0x45, 0x53, 0x4b }; // "RUST+DESK"
        public static readonly byte[] ObfuscatedSecret = new byte[] { $secretStr };
        public static readonly byte[] ObfuscatedUrl = new byte[] { $urlStr };
        public static readonly byte[] ObfuscatedSupabaseUrl = new byte[] { $sbUrlStr };
        public static readonly byte[] ObfuscatedSupabaseAnonKey = new byte[] { $sbAnonStr };
    }
}
"@

$outputPath = Join-Path $ProjectDir "Services\Data\ObfuscatedSecrets.cs"
$outputDir = Split-Path $outputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

[System.IO.File]::WriteAllText($outputPath, $code)
Write-Host "Generated obfuscated secrets successfully at $outputPath"
